version: '3'
services:
  database:
    image: postgres
    env_file: .env
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    #- ./database/create-db.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  frontend:
    image: km-front:v1.1.0
    env_file: .env
    ports:
    - 80:80
    depends_on:
    - backend
  backend:
    image: km-back:v1.2.1
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    # ports:
    # - 3000:3000

volumes:
  postgres_data: 