version: '3'
services:
  database:
    image: postgres
    env_file: .env
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./database/create-db.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
    - 5432:5432
  frontend:
    image: km-front:v1.0.13
    env_file: .env
    ports:
    - 80:80
    depends_on:
    - backend
  backend:
    image: km-back:v1.0.6
    env_file: .env
    ports:
    - 3000:3000

volumes:
  postgres_data: 