apiVersion: v1
kind: Secret
metadata:
  name: database-login
  namespace: message-application
  labels:
    app: km-message
type: Opaque
data:
  # All in base64
  PG_DATABASE: bWVzZGIK
  PG_PASSWORD: cGFzczE=
  PG_USER: YWRtaW4=