apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: message-application
  labels:
    app: km-message
spec:
  clusterIP: None
  selector:
    name: database
    app: km-message
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432