apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: message-application
  labels:
    app: km-message
spec:
  selector:
    name: backend
    app: km-message
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000