apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: message-application
  labels:
    app: km-message
spec:
  selector:
    name: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80