apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: message-application
  labels:
   app: km-message
spec:
  selector:
    matchLabels:
      name: database
      app: km-message
  replicas: 1
  serviceName: "database"
  template:
    metadata:
      labels:
        name: database
        app: km-message
    spec:
      containers:
      - name: database
        image: postgres
        env:
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: database-cm
              key: PGDATA
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: database-login
              key: PG_DATABASE
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-login
              key: PG_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-login
              key: PG_USER
        ports:
        - containerPort: 5432
          name: db-port
        volumeMounts:
        - name: db-data
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Mi